#!/usr/bin/env node
/// <reference types="node" />
/**
 * generate-tokens — `src/tokens/source.ts` is the truth; this renders `src/tokens.css`, the file
 * BOTH astrobot and astrocalendar import (PD-4, phase 53). Neither app owns a token value any
 * more — a change here (or in `source.ts`) is the only way either app's design language moves.
 *
 *   tsx scripts/generate-tokens.ts          → write src/tokens.css
 *   tsx scripts/generate-tokens.ts --check  → diff (EOL-normalized) against the committed file,
 *                                              exit 1 on drift (this is `npm run check:tokens`)
 */
import { readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { THEME, ROOT, DARK } from "../src/tokens/source.ts"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(HERE, "..", "src", "tokens.css")
const CHECK = process.argv.includes("--check")

function block(selector: string, lines: readonly string[]): string {
  return `${selector} {\n${lines.map((l) => `  ${l}`).join("\n")}\n}\n`
}

export function render(): string {
  const header = "/* GENERATED by scripts/generate-tokens.ts from src/tokens/source.ts — do not edit by hand. */\n"
  const theme = block("@theme inline", THEME)
  const root = block(":root", ROOT)
  const dark = block(".dark", DARK)
  return [header, theme, root, dark].join("\n").replace(/\r\n/g, "\n")
}

// Only act when run directly (`tsx scripts/generate-tokens.ts[...]`) — `tokens.test.ts` dynamically
// imports this module purely for `render()`, and an import must never have a side effect (it would
// otherwise silently (re)write `tokens.css` the instant the test file loads it).
const isMain = process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)

if (isMain) {
  const next = render()
  if (CHECK) {
    let committed: string
    try {
      committed = readFileSync(OUT, "utf8").replace(/\r\n/g, "\n")
    } catch {
      console.error(`✖ ${path.relative(process.cwd(), OUT)} does not exist — run \`npm run generate\`.`)
      process.exit(1)
    }
    if (committed !== next) {
      console.error(`✖ ${path.relative(process.cwd(), OUT)} is stale — source.ts changed; run \`npm run generate\`.`)
      process.exit(1)
    }
    console.log(`✓ ${path.relative(process.cwd(), OUT)} matches src/tokens/source.ts`)
  } else {
    writeFileSync(OUT, next)
    console.log(`wrote ${path.relative(process.cwd(), OUT)}`)
  }
}
